export enum ExportDataTypes {
  CUSTOM_COMMANDS_BROADCASTS = "CUSTOM_COMMANDS_BROADCASTS",
  ENV = "ENV",
  ENV_STRINGS = "ENV_STRINGS",
  MOONPIE = "MOONPIE",
  OSU_REQUESTS_CONFIG = "OSU_REQUESTS_CONFIG",
}
