import { SPOTIFY_STRING_ID } from "../spotify";

export const SPOTIFY_COMMAND_REPLY_STRING_ID = `${SPOTIFY_STRING_ID}_COMMAND_REPLY`;

export const spotifyCommandReplySong = {
  id: `${SPOTIFY_COMMAND_REPLY_STRING_ID}_SONG`,
  default:
    "@$(USER) Currently playing $(SPOTIFY_CURRENT_PREVIOUS_SONG|$(SHOW_IF_TRUE=%SPOTIFY_CURRENT_PREVIOUS_SONG:HAS_CURRENT%|'%SPOTIFY_CURRENT_PREVIOUS_SONG:CURRENT_TITLE%' by '%SPOTIFY_CURRENT_PREVIOUS_SONG:CURRENT_ARTISTS%'$(SHOW_IF_FALSE=%SPOTIFY_CURRENT_PREVIOUS_SONG:CURRENT_IS_SINGLE%| from '%SPOTIFY_CURRENT_PREVIOUS_SONG:CURRENT_ALBUM%'))$(SHOW_IF_FALSE=%SPOTIFY_CURRENT_PREVIOUS_SONG:HAS_CURRENT%|no song)$(SHOW_IF_TRUE=%SPOTIFY_CURRENT_PREVIOUS_SONG:HAS_PREVIOUS%|, previously played '%SPOTIFY_CURRENT_PREVIOUS_SONG:PREVIOUS_TITLE%' by '%SPOTIFY_CURRENT_PREVIOUS_SONG:PREVIOUS_ARTISTS%'$(SHOW_IF_FALSE=%SPOTIFY_CURRENT_PREVIOUS_SONG:PREVIOUS_IS_SINGLE%| from '%SPOTIFY_CURRENT_PREVIOUS_SONG:PREVIOUS_ALBUM%')))",
};

export const spotifyCommandReply: Iterable<readonly [string, string]> = [
  [spotifyCommandReplySong.id, spotifyCommandReplySong.default],
];
