# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  # Run CI when a new version tag is created
  create:
    tags:
      - v*
  # Run CI when a new commit is pushed
  push:
    branches: [ main, dev ]
  # Run CI when a new pull request is created
  pull_request:
    branches: [ main, dev ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Run tests and see code coverage
      run: npm run test
    - name: Build the bot
      run: npm run build
    - name: Lint the code
      run: npm run lint
    - name: Create documentation
      run: npm run docs
    - name: Create binary release
      run: npm run package:linux
    - name: Save binary artifact
      uses: actions/upload-artifact@v3
      with:
        name: moonpiebot-linux-node-${{ matrix.node-version }}
        path: bin/moonpiebot
        retention-days: 14
        if-no-files-found: error


# TODO: Arch Linux Package Builds


  build-windows:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Run tests and see code coverage
      run: npm run test
    - name: Build the bot
      run: npm run build
    - name: Lint the code
      run: npm run lint
    - name: Create documentation
      run: npm run docs
    - name: Create binary release
      run: npm run package:win
    - name: Save binary artifact [standalone]
      uses: actions/upload-artifact@v3
      with:
        name: moonpiebot-windows-node-${{ matrix.node-version }}
        path: bin/moonpiebot.exe
        retention-days: 14
        if-no-files-found: error
    - name: Create installer
      run: makensis .\windows_installer.nsi
      working-directory: .\installer
    - name: Save binary artifact [installer]
      uses: actions/upload-artifact@v3
      with:
        name: moonpiebot-installer-windows-node-${{ matrix.node-version }}
        path: bin/moonpiebot_setup.exe
        retention-days: 14
        if-no-files-found: error


  update-documentation:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Create documentation
      run: npm run docs
    - run: |
        mkdir -p ./docs/res/icons
        cp res/icons/moonpiebot.png ./docs/res/icons/
    - name: Deploy to GitHub Pages
      # Only deploy the website when pushing on the main branch
      if: github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: ./docs # The folder the action should deploy.
