# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  # Run CI when a new version tag is created
  create:
    tags:
      - v*
  # Run CI when a new commit is pushed
  push:
    branches: [ main, dev ]
  # Run CI when a new pull request is created
  pull_request:
    branches: [ main, dev ]

jobs:


  build:

    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest,windows-latest]
        include:
          - os: ubuntu-latest
            os-name: linux
            binary-name: moonpiebot
          - os: windows-latest
            os-name: windows
            binary-name: moonpiebot.exe
            binary-name-installer: moonpiebot_setup.exe

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies (apt)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install graphviz
    - name: Install dependencies (choco)
      if: matrix.os == 'windows-latest'
      run: choco install graphviz
    - name: Install dependencies (npm)
      run: npm ci
    - name: Run tests and see code coverage
      run: npm run test
    - name: Build the bot
      run: npm run build
    - name: Lint the code
      run: npm run lint
    - name: Create documentation
      run: npm run docs
    - name: Create files
      run: |
        npm run create:manPage
        npm run create:jsonSchemas
    - name: Create binary release
      run: npm run package:${{ matrix.os-name }}
    - name: Save binary artifact [standalone]
      uses: actions/upload-artifact@v3
      with:
        name: moonpiebot-${{ matrix.os-name }}-node-${{ matrix.node-version }}
        path: bin/${{ matrix.binary-name }}
        retention-days: 14
        if-no-files-found: error
    - name: Create installer
      if: matrix.os == 'windows-latest'
      run: makensis .\windows_installer.nsi
      working-directory: .\installer
    - name: Save binary artifact [installer]
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v3
      with:
        name: moonpiebot-installer-${{ matrix.os-name }}-node-${{ matrix.node-version }}
        path: bin/${{ matrix.binary-name-installer }}
        retention-days: 14
        if-no-files-found: error


  update-documentation:

    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    # Only update documentation if the build didn't fail and happened on the main branch
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies (apt)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install graphviz
    - name: Install dependencies (choco)
      if: matrix.os == 'windows-latest'
      run: choco install graphviz
    - name: Install dependencies (npm)
      run: npm ci
    - name: Create documentation
      run: npm run docs
    - name: Copy moonpiebot icon
      if: matrix.os == 'ubuntu-latest'
      run: |
        mkdir -p ./docs/res/icons
        cp res/icons/moonpiebot.png ./docs/res/icons/
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs # The folder the action should deploy.
